language: python
python:
  - 2.7

env:
  global:
    - CORE_BRANCH=stable7

branches:
  only:
    - travis_tests

before_install:
- sudo apt-get update
- sudo apt-get install -y libxml2-dev
- sudo apt-get install apache2 mysql-server libapache2-mod-php5
- sudo apt-get install php5-gd php5-json php5-mysql php5-curl
- sudo apt-get install php5-intl php5-cli php5-mcrypt php5-imagick
- sudo service apache2 restart

install:
  - bash ./before_install.sh $CORE_BRANCH

script:
  # execute unit tests
  - ./runtests.sh
