language: php
php:
  - 5.3

env:
  global:
    - CORE_BRANCH=stable7

branches:
  only:
    - travis_tests

before_install:
- sudo apt-get update
- sudo apt-get install python-software-properties
- sudo apt-get install python python-pip
- sudo pip install requests

install:
  - bash ./before_install.sh $CORE_BRANCH

script:
  # execute unit tests
  - ./runtests.sh
