language: python
python:
  - 2.7

env:
  global:
    - CORE_BRANCH=master

branches:
  only:
    - travis_tests

before_install:
- sudo apt-get update
- sudo apt-get install php5 php5-mysql php5-gd

install:
  - bash ./before_install.sh $CORE_BRANCH

script:
  # execute unit tests
  - ./runtests.sh
