language: php
php:
  - "5.4"

env:
  global:
    - CORE_BRANCH=stable7

branches:
  only:
    - travis_tests

before_install:
- sudo apt-get update
- sudo pip install requests

install:
  - bash ./install_php_apache.sh
  - bash ./before_install.sh $CORE_BRANCH

script:
  # execute unit tests
  - ./runtests.sh
