language: php
php:
  - "5.4"

env:
  global:
    - CORE_BRANCH=stable7

branches:
  only:
    - travis_tests

before_install:
- sudo apt-get update
- sudo pip install requests

install:
  - bash ./before_install.sh $CORE_BRANCH
  - bash ./install_php_apache.sh

script: curl -s http://localhost/ && sudo cat /var/log/apache2/error.log && curl -s http://localhost/ | grep -F "hello world! $TRAVIS_PHP_VERSION" && curl -s http://localhost/non_existing_url_is_redirected | grep -F "hello world! $TRAVIS_PHP_VERSION" && curl -s http://mydomain.local/ | grep -F "hello world! $TRAVIS_PHP_VERSION"

#script:
#  # execute unit tests
#  - ./runtests.sh
